version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: accounts-and-transactions
    depends_on:
      - mysql
    environment:
      - DB_HOST=my-mysql
      - AUTO_MIGRATE_REQUIRED=true
    ports:
      - "8080:8080"
    restart: always

volumes:
  mysql-data:
