// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "accounts-and-transactions/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

// RegisterTransaction provides a mock function with given fields: ctx, account, transaction
func (_m *TransactionRepository) RegisterTransaction(ctx context.Context, account *entity.Account, transaction *entity.Transaction) (*entity.Transaction, error) {
	ret := _m.Called(ctx, account, transaction)

	if len(ret) == 0 {
		panic("no return value specified for RegisterTransaction")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Account, *entity.Transaction) (*entity.Transaction, error)); ok {
		return rf(ctx, account, transaction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Account, *entity.Transaction) *entity.Transaction); ok {
		r0 = rf(ctx, account, transaction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Account, *entity.Transaction) error); ok {
		r1 = rf(ctx, account, transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
